### PR TITLE
refactor(app): :recycle: use plain chan polling

### PR DESCRIPTION
**Pull request by ninedraft**
Select without default branch with over a single chan is equal to hust a plain channerl polling

### CODE REVIEW

**Comment by anmitsu** [comment]
This will block app because polled results not be passed to the event handler.
This problem occurs when files copy/move overwrite confirming.
Please add event handling as follow.
```go
ev := g.event
g.eventHandler(ev)
```

**Comment by ninedraft** [comment]
Oh, my bad. I'll fix it at next 24 hours

**Comment by ninedraft** [comment]
@anmitsu :heavy_check_mark:

**Comment by anmitsu** [comment]
@ninedraft Thanks.

**Pull request merged**
