### PR TITLE
build(go module): :pushpin: bump go version to 1.16

### PR DESCRIPTION
**Pull request by ninedraft**
New `fs` package can be very useful for this project. Consider to bump go version to 1.16

### CODE REVIEW

**Comment by anmitsu** [comment]
I don't understand why specify Go version in go.mod.
What will change if bump to Go version 1.16 of go.mod?

**Comment by ninedraft** [comment]
You will be able to use go1.16 features
Look here: https://github.com/ninedraft/go-module-example
Modules `go1.16` and `go1.15` are identical except `go $VERSION` directive in `go.mod`.

Module go1.15 emits error `.\main.go:8:3: go:embed requires go1.16 or later (-lang was set to go1.15; check go.mod)` on compilation, while `go1.16`-s main package can be build without errors.

**Comment by anmitsu** [comment]
I don't need 1.16 feature right away, this to merge if there is no problem in previous Go version users.

**Comment by ninedraft** [comment]
Users of older versions of Go will not be able to build this project only if it uses the features of the new version.

To be honest, I'm currently working on a temporarily hidden PR for your project, in which I want to propose a new engine for navigating arbitrary filesystems. For example, for files inside zip and gz archives or SFTP endpoint. So this PR is essentially my selfish motives :)

**Comment by anmitsu** [comment]
OK. Thanks for answering my question.
I look forward to your work.

**Pull request merged**
